coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

  range: '70...90'

flags:
  cli:
    paths:
      - packages/cli/src
  core:
    paths:
      - packages/core/src
  excel-engine:
    paths:
      - packages/excel-engine/src
  shared:
    paths:
      - packages/shared/src

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false

